version: "3.9"

services:
  broker-0:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker-0:9093
      - KAFKA_KRAFT_CLUSTER_ID=YmZkNjkzNTQzYjI3MTFmMG
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - broker_0_data:/bitnami/kafka
    networks:
      - kafka-network

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    platform: linux/amd64
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker-0
    environment:
      - KSQL_BOOTSTRAP_SERVERS=broker-0:9092
      - KSQL_LISTENERS=http://0.0.0.0:8088
      - KSQL_KSQL_SERVICE_ID=ksqldb_
      - KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET=earliest
      - KSQL_OPTS=-Xmx2g -Xms1g               # <-- ВАЖНО! (можешь увеличить до 3g/2g, если прям много памяти)
      - KSQL_DEBUG=true                       # <-- Для большего логирования ошибок
    ports:
      - "8088:8088"
    networks:
      - kafka-network
    restart: always                           # <-- Если процесс умрет, контейнер перезапустится
    # mem_limit: 2g                           # <-- не используй! Колима лимитирует память сама

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    platform: linux/amd64
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    networks:
      - kafka-network

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=lab_02_task_02_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=broker-0:9092
      - KAFKA_CLUSTERS_0_KSQLDBSERVER=http://ksqldb-server:8088
    networks:
      - kafka-network

volumes:
  broker_0_data:

networks:
  kafka-network:
    driver: bridge
