version: "3.9"

services:
  broker-0:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"  # порт, на который смогут подключаться внешние клиенты
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes    # разрешение использования нешифрованного соединения
      - KAFKA_CFG_NODE_ID=0             # уникальный ID узла в кластере
      - KAFKA_CFG_PROCESS_ROLES=broker,controller           # роли узла в кластере
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER      # название слушателя, который будет использоваться для управления кластером
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker-0:9093,1@broker-1:9093,2@broker-2:9093    # какие узлы отвечают за голосование в кворуме контроллеров
      - KAFKA_KRAFT_CLUSTER_ID=YzQwMGQyNDYyNzgxMTFmMD                                                          # ID кластера
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094          # слушатель: порт
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-0:9092,EXTERNAL://127.0.0.1:9094  # адреса, через которые клиенты могут соединяться с узлами
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT  # какие протоколы безопасности использовать
    volumes:
      - broker_0_data:/bitnami/kafka
    networks:
      - kafka-network

  broker-1:
    image: bitnami/kafka:3.4
    ports:
      - "9095:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker-0:9093,1@broker-1:9093,2@broker-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=YzQwMGQyNDYyNzgxMTFmMD
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - broker_1_data:/bitnami/kafka
    networks:
      - kafka-network

  broker-2:
    image: bitnami/kafka:3.4
    ports:
      - "9096:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker-0:9093,1@broker-1:9093,2@broker-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=YzQwMGQyNDYyNzgxMTFmMD
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - broker_2_data:/bitnami/kafka
    networks:
      - kafka-network

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=broker-0:9092,broker-1:9092,broker-2:9092
      - KAFKA_CLUSTERS_0_NAME=lab_01_kraft_cluster
    networks:
      - kafka-network

volumes:
  broker_0_data:
  broker_1_data:
  broker_2_data:

networks:
  kafka-network:
    driver: bridge
