version: '3.8'
services:
  app_ui:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker-0:9092
    command: python src/ui/ui.py
    networks:
      - task_01_kafka-network

  msg_handler:
    build: ./app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka://broker-0:9092,kafka://broker-1:9092,kafka://broker-2:9092
      - KAFKA_MEMORY_TYPE=rocksdb://
    command: 
      faust -A src.services.internal_msg_handler worker -l info
    networks:
      - task_01_kafka-network

networks:
  task_01_kafka-network:
    external: true
