{
 "title": "Prod Kafka Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "prod" }
  ]
 },
 "panels": [
  {
   "title": "Количество брокеров",
   "type": "barchart",
   "description": "Контроль доступности нод",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_brokers{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доступность экспортера",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Топ 10 топиков по количеству партиций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by (topic) (kafka_topic_partitions{cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рост оффсетов",
   "type": "timeseries",
   "description": "Активность producers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{topic}} {{partition}}"
    }
   ]
  },
  {
   "title": "CPU экспортера",
   "type": "timeseries",
   "description": "Перегрузка",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Память экспортера",
   "type": "timeseries",
   "description": "Утечки",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}