{
 "title": "Test dash",
 "time": { "from": "2025-06-15T20:12:30.719Z", "to": "2025-06-15T20:17:06.051Z" },
 "panels": [
  {
   "title": "Количество задач коннектора",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_total_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_failed_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_running_task_count",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Количество ошибок коннектора",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_errors_logged",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость передачи данных",
   "type": "timeseries",
   "description": "Из Kafka Connect в Kafka Broker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество потоков в ожидании отправки",
   "type": "timeseries",
   "description": "Количество потоков Kafka Producer в ожидании отправки",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_waiting_threads",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}