version: '3.8'
services:
  producer:
    build: .
    environment:
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    command: python Producer.py
    networks:
      - lab_01_kafka-network

  single_message_consumer:
    build: .
    environment:
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_GROUP_ID=single_message_consumer
      - KAFKA_ENABLE_AUTO_COMMIT=True     # Включить автоматический коммит оффсетов
      - KAFKA_AUTO_OFFSET_RESET=earliest  # Начинаем с начала, если нет коммитов оффсетов
    command: python SingleMessageConsumer.py
    deploy:  
      replicas: 2
    networks:
      - lab_01_kafka-network

  batch_message_consumer:
    build: .
    environment:
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_GROUP_ID=batch_message_consumer
      - KAFKA_ENABLE_AUTO_COMMIT=False
      - KAFKA_AUTO_OFFSET_RESET=earliest
    command: python BatchMessageConsumer.py
    deploy:  
      replicas: 2
    networks:
      - lab_01_kafka-network

networks:
  lab_01_kafka-network:
    external: true
